// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package sdk represents the world "grafbase:sdk/sdk".
package sdk

import (
	"example.com/grafbase-go-extension/grafbase/sdk/schema"
)

// Schema represents the type alias "grafbase:sdk/sdk#schema".
//
// See [schema.Schema] for more information.
type Schema = schema.Schema
