// Code generated by wit-bindgen-go. DO NOT EDIT.

package sdk

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "grafbase:sdk/sdk".
var Exports struct {
	// RegisterExtension represents the caller-defined, exported function "register-extension".
	//
	// The extension registration function. Must be called before initialization.
	//
	//	register-extension: func()
	RegisterExtension func()

	// Init represents the caller-defined, exported function "init".
	//
	// initialization function called to set up the wasm extension
	// if an error happens here, the gateway will refuse to continue.
	// Receives a list of schema directives associated with the extension
	//
	//	init: func(schemas: list<tuple<string, schema>>, configuration: list<u8>, can-skip-sending-events:
	//	bool) -> result<_, string>
	Init func(schemas cm.List[cm.Tuple[string, Schema]], configuration cm.List[uint8], canSkipSendingEvents bool) (result cm.Result[string, struct{}, string])
}
