// Generated by `wit-bindgen` 0.25.0. DO NOT EDIT!
// Options used:
#[allow(dead_code)]
pub mod component {
    #[allow(dead_code)]
    pub mod grafbase {
        #[allow(dead_code, clippy::all)]
        pub mod types {
            #[used]
            #[doc(hidden)]
            #[cfg(target_arch = "wasm32")]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, PartialEq)]
            pub enum HeaderError {
                InvalidHeaderValue,
                InvalidHeaderName,
            }
            impl HeaderError {
                pub fn name(&self) -> &'static str {
                    match self {
                        HeaderError::InvalidHeaderValue => "invalid-header-value",
                        HeaderError::InvalidHeaderName => "invalid-header-name",
                    }
                }
                pub fn message(&self) -> &'static str {
                    match self {
                        HeaderError::InvalidHeaderValue => "",
                        HeaderError::InvalidHeaderName => "",
                    }
                }
            }
            impl ::core::fmt::Debug for HeaderError {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    f.debug_struct("HeaderError")
                        .field("code", &(*self as i32))
                        .field("name", &self.name())
                        .field("message", &self.message())
                        .finish()
                }
            }
            impl ::core::fmt::Display for HeaderError {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    write!(f, "{} (error {})", self.name(), *self as i32)
                }
            }

            impl std::error::Error for HeaderError {}

            impl HeaderError {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> HeaderError {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }

                    match val {
                        0 => HeaderError::InvalidHeaderValue,
                        1 => HeaderError::InvalidHeaderName,

                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }

            #[derive(Debug)]
            #[repr(transparent)]
            pub struct Context {
                handle: _rt::Resource<Context>,
            }

            impl Context {
                #[doc(hidden)]
                pub unsafe fn from_handle(handle: u32) -> Self {
                    Self {
                        handle: _rt::Resource::from_handle(handle),
                    }
                }

                #[doc(hidden)]
                pub fn take_handle(&self) -> u32 {
                    _rt::Resource::take_handle(&self.handle)
                }

                #[doc(hidden)]
                pub fn handle(&self) -> u32 {
                    _rt::Resource::handle(&self.handle)
                }
            }

            unsafe impl _rt::WasmResource for Context {
                #[inline]
                unsafe fn drop(_handle: u32) {
                    #[cfg(not(target_arch = "wasm32"))]
                    unreachable!();

                    #[cfg(target_arch = "wasm32")]
                    {
                        #[link(wasm_import_module = "component:grafbase/types")]
                        extern "C" {
                            #[link_name = "[resource-drop]context"]
                            fn drop(_: u32);
                        }

                        drop(_handle);
                    }
                }
            }

            #[derive(Debug)]
            #[repr(transparent)]
            pub struct SharedContext {
                handle: _rt::Resource<SharedContext>,
            }

            impl SharedContext {
                #[doc(hidden)]
                pub unsafe fn from_handle(handle: u32) -> Self {
                    Self {
                        handle: _rt::Resource::from_handle(handle),
                    }
                }

                #[doc(hidden)]
                pub fn take_handle(&self) -> u32 {
                    _rt::Resource::take_handle(&self.handle)
                }

                #[doc(hidden)]
                pub fn handle(&self) -> u32 {
                    _rt::Resource::handle(&self.handle)
                }
            }

            unsafe impl _rt::WasmResource for SharedContext {
                #[inline]
                unsafe fn drop(_handle: u32) {
                    #[cfg(not(target_arch = "wasm32"))]
                    unreachable!();

                    #[cfg(target_arch = "wasm32")]
                    {
                        #[link(wasm_import_module = "component:grafbase/types")]
                        extern "C" {
                            #[link_name = "[resource-drop]shared-context"]
                            fn drop(_: u32);
                        }

                        drop(_handle);
                    }
                }
            }

            #[derive(Debug)]
            #[repr(transparent)]
            pub struct Headers {
                handle: _rt::Resource<Headers>,
            }

            impl Headers {
                #[doc(hidden)]
                pub unsafe fn from_handle(handle: u32) -> Self {
                    Self {
                        handle: _rt::Resource::from_handle(handle),
                    }
                }

                #[doc(hidden)]
                pub fn take_handle(&self) -> u32 {
                    _rt::Resource::take_handle(&self.handle)
                }

                #[doc(hidden)]
                pub fn handle(&self) -> u32 {
                    _rt::Resource::handle(&self.handle)
                }
            }

            unsafe impl _rt::WasmResource for Headers {
                #[inline]
                unsafe fn drop(_handle: u32) {
                    #[cfg(not(target_arch = "wasm32"))]
                    unreachable!();

                    #[cfg(target_arch = "wasm32")]
                    {
                        #[link(wasm_import_module = "component:grafbase/types")]
                        extern "C" {
                            #[link_name = "[resource-drop]headers"]
                            fn drop(_: u32);
                        }

                        drop(_handle);
                    }
                }
            }

            #[derive(Clone)]
            pub struct ErrorResponse {
                pub message: _rt::String,
                pub extensions: _rt::Vec<(_rt::String, _rt::String)>,
            }
            impl ::core::fmt::Debug for ErrorResponse {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    f.debug_struct("ErrorResponse")
                        .field("message", &self.message)
                        .field("extensions", &self.extensions)
                        .finish()
                }
            }
            impl ::core::fmt::Display for ErrorResponse {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    write!(f, "{:?}", self)
                }
            }
            impl std::error::Error for ErrorResponse {}
            impl Context {
                #[allow(unused_unsafe, clippy::all)]
                pub fn get(&self, name: &str) -> Option<_rt::String> {
                    unsafe {
                        #[repr(align(4))]
                        struct RetArea([::core::mem::MaybeUninit<u8>; 12]);
                        let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 12]);
                        let vec0 = name;
                        let ptr0 = vec0.as_ptr().cast::<u8>();
                        let len0 = vec0.len();
                        let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
                        #[cfg(target_arch = "wasm32")]
                        #[link(wasm_import_module = "component:grafbase/types")]
                        extern "C" {
                            #[link_name = "[method]context.get"]
                            fn wit_import(_: i32, _: *mut u8, _: usize, _: *mut u8);
                        }

                        #[cfg(not(target_arch = "wasm32"))]
                        fn wit_import(_: i32, _: *mut u8, _: usize, _: *mut u8) {
                            unreachable!()
                        }
                        wit_import((self).handle() as i32, ptr0.cast_mut(), len0, ptr1);
                        let l2 = i32::from(*ptr1.add(0).cast::<u8>());
                        match l2 {
                            0 => None,
                            1 => {
                                let e = {
                                    let l3 = *ptr1.add(4).cast::<*mut u8>();
                                    let l4 = *ptr1.add(8).cast::<usize>();
                                    let len5 = l4;
                                    let bytes5 = _rt::Vec::from_raw_parts(l3.cast(), len5, len5);

                                    _rt::string_lift(bytes5)
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        }
                    }
                }
            }
            impl Context {
                #[allow(unused_unsafe, clippy::all)]
                pub fn set(&self, name: &str, value: &str) {
                    unsafe {
                        let vec0 = name;
                        let ptr0 = vec0.as_ptr().cast::<u8>();
                        let len0 = vec0.len();
                        let vec1 = value;
                        let ptr1 = vec1.as_ptr().cast::<u8>();
                        let len1 = vec1.len();

                        #[cfg(target_arch = "wasm32")]
                        #[link(wasm_import_module = "component:grafbase/types")]
                        extern "C" {
                            #[link_name = "[method]context.set"]
                            fn wit_import(_: i32, _: *mut u8, _: usize, _: *mut u8, _: usize);
                        }

                        #[cfg(not(target_arch = "wasm32"))]
                        fn wit_import(_: i32, _: *mut u8, _: usize, _: *mut u8, _: usize) {
                            unreachable!()
                        }
                        wit_import((self).handle() as i32, ptr0.cast_mut(), len0, ptr1.cast_mut(), len1);
                    }
                }
            }
            impl Context {
                #[allow(unused_unsafe, clippy::all)]
                pub fn delete(&self, name: &str) -> Option<_rt::String> {
                    unsafe {
                        #[repr(align(4))]
                        struct RetArea([::core::mem::MaybeUninit<u8>; 12]);
                        let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 12]);
                        let vec0 = name;
                        let ptr0 = vec0.as_ptr().cast::<u8>();
                        let len0 = vec0.len();
                        let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
                        #[cfg(target_arch = "wasm32")]
                        #[link(wasm_import_module = "component:grafbase/types")]
                        extern "C" {
                            #[link_name = "[method]context.delete"]
                            fn wit_import(_: i32, _: *mut u8, _: usize, _: *mut u8);
                        }

                        #[cfg(not(target_arch = "wasm32"))]
                        fn wit_import(_: i32, _: *mut u8, _: usize, _: *mut u8) {
                            unreachable!()
                        }
                        wit_import((self).handle() as i32, ptr0.cast_mut(), len0, ptr1);
                        let l2 = i32::from(*ptr1.add(0).cast::<u8>());
                        match l2 {
                            0 => None,
                            1 => {
                                let e = {
                                    let l3 = *ptr1.add(4).cast::<*mut u8>();
                                    let l4 = *ptr1.add(8).cast::<usize>();
                                    let len5 = l4;
                                    let bytes5 = _rt::Vec::from_raw_parts(l3.cast(), len5, len5);

                                    _rt::string_lift(bytes5)
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        }
                    }
                }
            }
            impl SharedContext {
                #[allow(unused_unsafe, clippy::all)]
                pub fn get(&self, name: &str) -> Option<_rt::String> {
                    unsafe {
                        #[repr(align(4))]
                        struct RetArea([::core::mem::MaybeUninit<u8>; 12]);
                        let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 12]);
                        let vec0 = name;
                        let ptr0 = vec0.as_ptr().cast::<u8>();
                        let len0 = vec0.len();
                        let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
                        #[cfg(target_arch = "wasm32")]
                        #[link(wasm_import_module = "component:grafbase/types")]
                        extern "C" {
                            #[link_name = "[method]shared-context.get"]
                            fn wit_import(_: i32, _: *mut u8, _: usize, _: *mut u8);
                        }

                        #[cfg(not(target_arch = "wasm32"))]
                        fn wit_import(_: i32, _: *mut u8, _: usize, _: *mut u8) {
                            unreachable!()
                        }
                        wit_import((self).handle() as i32, ptr0.cast_mut(), len0, ptr1);
                        let l2 = i32::from(*ptr1.add(0).cast::<u8>());
                        match l2 {
                            0 => None,
                            1 => {
                                let e = {
                                    let l3 = *ptr1.add(4).cast::<*mut u8>();
                                    let l4 = *ptr1.add(8).cast::<usize>();
                                    let len5 = l4;
                                    let bytes5 = _rt::Vec::from_raw_parts(l3.cast(), len5, len5);

                                    _rt::string_lift(bytes5)
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        }
                    }
                }
            }
            impl Headers {
                #[allow(unused_unsafe, clippy::all)]
                pub fn get(&self, name: &str) -> Result<Option<_rt::String>, HeaderError> {
                    unsafe {
                        #[repr(align(4))]
                        struct RetArea([::core::mem::MaybeUninit<u8>; 16]);
                        let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 16]);
                        let vec0 = name;
                        let ptr0 = vec0.as_ptr().cast::<u8>();
                        let len0 = vec0.len();
                        let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
                        #[cfg(target_arch = "wasm32")]
                        #[link(wasm_import_module = "component:grafbase/types")]
                        extern "C" {
                            #[link_name = "[method]headers.get"]
                            fn wit_import(_: i32, _: *mut u8, _: usize, _: *mut u8);
                        }

                        #[cfg(not(target_arch = "wasm32"))]
                        fn wit_import(_: i32, _: *mut u8, _: usize, _: *mut u8) {
                            unreachable!()
                        }
                        wit_import((self).handle() as i32, ptr0.cast_mut(), len0, ptr1);
                        let l2 = i32::from(*ptr1.add(0).cast::<u8>());
                        match l2 {
                            0 => {
                                let e = {
                                    let l3 = i32::from(*ptr1.add(4).cast::<u8>());

                                    match l3 {
                                        0 => None,
                                        1 => {
                                            let e = {
                                                let l4 = *ptr1.add(8).cast::<*mut u8>();
                                                let l5 = *ptr1.add(12).cast::<usize>();
                                                let len6 = l5;
                                                let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);

                                                _rt::string_lift(bytes6)
                                            };
                                            Some(e)
                                        }
                                        _ => _rt::invalid_enum_discriminant(),
                                    }
                                };
                                Ok(e)
                            }
                            1 => {
                                let e = {
                                    let l7 = i32::from(*ptr1.add(4).cast::<u8>());

                                    HeaderError::_lift(l7 as u8)
                                };
                                Err(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        }
                    }
                }
            }
            impl Headers {
                #[allow(unused_unsafe, clippy::all)]
                pub fn set(&self, name: &str, value: &str) -> Result<(), HeaderError> {
                    unsafe {
                        #[repr(align(1))]
                        struct RetArea([::core::mem::MaybeUninit<u8>; 2]);
                        let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 2]);
                        let vec0 = name;
                        let ptr0 = vec0.as_ptr().cast::<u8>();
                        let len0 = vec0.len();
                        let vec1 = value;
                        let ptr1 = vec1.as_ptr().cast::<u8>();
                        let len1 = vec1.len();
                        let ptr2 = ret_area.0.as_mut_ptr().cast::<u8>();
                        #[cfg(target_arch = "wasm32")]
                        #[link(wasm_import_module = "component:grafbase/types")]
                        extern "C" {
                            #[link_name = "[method]headers.set"]
                            fn wit_import(_: i32, _: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8);
                        }

                        #[cfg(not(target_arch = "wasm32"))]
                        fn wit_import(_: i32, _: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8) {
                            unreachable!()
                        }
                        wit_import(
                            (self).handle() as i32,
                            ptr0.cast_mut(),
                            len0,
                            ptr1.cast_mut(),
                            len1,
                            ptr2,
                        );
                        let l3 = i32::from(*ptr2.add(0).cast::<u8>());
                        match l3 {
                            0 => {
                                let e = ();
                                Ok(e)
                            }
                            1 => {
                                let e = {
                                    let l4 = i32::from(*ptr2.add(1).cast::<u8>());

                                    HeaderError::_lift(l4 as u8)
                                };
                                Err(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        }
                    }
                }
            }
            impl Headers {
                #[allow(unused_unsafe, clippy::all)]
                pub fn delete(&self, name: &str) -> Result<Option<_rt::String>, HeaderError> {
                    unsafe {
                        #[repr(align(4))]
                        struct RetArea([::core::mem::MaybeUninit<u8>; 16]);
                        let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 16]);
                        let vec0 = name;
                        let ptr0 = vec0.as_ptr().cast::<u8>();
                        let len0 = vec0.len();
                        let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
                        #[cfg(target_arch = "wasm32")]
                        #[link(wasm_import_module = "component:grafbase/types")]
                        extern "C" {
                            #[link_name = "[method]headers.delete"]
                            fn wit_import(_: i32, _: *mut u8, _: usize, _: *mut u8);
                        }

                        #[cfg(not(target_arch = "wasm32"))]
                        fn wit_import(_: i32, _: *mut u8, _: usize, _: *mut u8) {
                            unreachable!()
                        }
                        wit_import((self).handle() as i32, ptr0.cast_mut(), len0, ptr1);
                        let l2 = i32::from(*ptr1.add(0).cast::<u8>());
                        match l2 {
                            0 => {
                                let e = {
                                    let l3 = i32::from(*ptr1.add(4).cast::<u8>());

                                    match l3 {
                                        0 => None,
                                        1 => {
                                            let e = {
                                                let l4 = *ptr1.add(8).cast::<*mut u8>();
                                                let l5 = *ptr1.add(12).cast::<usize>();
                                                let len6 = l5;
                                                let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);

                                                _rt::string_lift(bytes6)
                                            };
                                            Some(e)
                                        }
                                        _ => _rt::invalid_enum_discriminant(),
                                    }
                                };
                                Ok(e)
                            }
                            1 => {
                                let e = {
                                    let l7 = i32::from(*ptr1.add(4).cast::<u8>());

                                    HeaderError::_lift(l7 as u8)
                                };
                                Err(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        }
                    }
                }
            }
        }
    }
}
#[allow(dead_code)]
pub mod exports {
    #[allow(dead_code)]
    pub mod component {
        #[allow(dead_code)]
        pub mod grafbase {
            #[allow(dead_code, clippy::all)]
            pub mod authorization {
                #[used]
                #[doc(hidden)]
                #[cfg(target_arch = "wasm32")]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type ErrorResponse = super::super::super::super::component::grafbase::types::ErrorResponse;
                pub type SharedContext = super::super::super::super::component::grafbase::types::SharedContext;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_authorized_cabi<T: Guest>(
                    arg0: i32,
                    arg1: *mut u8,
                    arg2: usize,
                    arg3: *mut u8,
                    arg4: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")]
                    _rt::run_ctors_once();
                    let len0 = arg2;
                    let bytes0 = _rt::Vec::from_raw_parts(arg1.cast(), len0, len0);
                    let base4 = arg3;
                    let len4 = arg4;
                    let mut result4 = _rt::Vec::with_capacity(len4);
                    for i in 0..len4 {
                        let base = base4.add(i * 8);
                        let e4 = {
                            let l1 = *base.add(0).cast::<*mut u8>();
                            let l2 = *base.add(4).cast::<usize>();
                            let len3 = l2;
                            let bytes3 = _rt::Vec::from_raw_parts(l1.cast(), len3, len3);

                            _rt::string_lift(bytes3)
                        };
                        result4.push(e4);
                    }
                    _rt::cabi_dealloc(base4, len4 * 8, 4);
                    let result5 = T::authorized(
                        super::super::super::super::component::grafbase::types::SharedContext::from_handle(arg0 as u32),
                        _rt::string_lift(bytes0),
                        result4,
                    );
                    let ptr6 = _RET_AREA.0.as_mut_ptr().cast::<u8>();
                    match result5 {
                        Ok(e) => {
                            *ptr6.add(0).cast::<u8>() = (0i32) as u8;
                            let vec13 = e;
                            let len13 = vec13.len();
                            let layout13 = _rt::alloc::Layout::from_size_align_unchecked(vec13.len() * 20, 4);
                            let result13 = if layout13.size() != 0 {
                                let ptr = _rt::alloc::alloc(layout13).cast::<u8>();
                                if ptr.is_null() {
                                    _rt::alloc::handle_alloc_error(layout13);
                                }
                                ptr
                            } else {
                                {
                                    ::core::ptr::null_mut()
                                }
                            };
                            for (i, e) in vec13.into_iter().enumerate() {
                                let base = result13.add(i * 20);
                                {
                                    match e {
                                        Some(e) => {
                                            *base.add(0).cast::<u8>() = (1i32) as u8;
                                            let super::super::super::super::component::grafbase::types::ErrorResponse {
                                                message: message7,
                                                extensions: extensions7,
                                            } = e;
                                            let vec8 = (message7.into_bytes()).into_boxed_slice();
                                            let ptr8 = vec8.as_ptr().cast::<u8>();
                                            let len8 = vec8.len();
                                            ::core::mem::forget(vec8);
                                            *base.add(8).cast::<usize>() = len8;
                                            *base.add(4).cast::<*mut u8>() = ptr8.cast_mut();
                                            let vec12 = extensions7;
                                            let len12 = vec12.len();
                                            let layout12 =
                                                _rt::alloc::Layout::from_size_align_unchecked(vec12.len() * 16, 4);
                                            let result12 = if layout12.size() != 0 {
                                                let ptr = _rt::alloc::alloc(layout12).cast::<u8>();
                                                if ptr.is_null() {
                                                    _rt::alloc::handle_alloc_error(layout12);
                                                }
                                                ptr
                                            } else {
                                                {
                                                    ::core::ptr::null_mut()
                                                }
                                            };
                                            for (i, e) in vec12.into_iter().enumerate() {
                                                let base = result12.add(i * 16);
                                                {
                                                    let (t9_0, t9_1) = e;
                                                    let vec10 = (t9_0.into_bytes()).into_boxed_slice();
                                                    let ptr10 = vec10.as_ptr().cast::<u8>();
                                                    let len10 = vec10.len();
                                                    ::core::mem::forget(vec10);
                                                    *base.add(4).cast::<usize>() = len10;
                                                    *base.add(0).cast::<*mut u8>() = ptr10.cast_mut();
                                                    let vec11 = (t9_1.into_bytes()).into_boxed_slice();
                                                    let ptr11 = vec11.as_ptr().cast::<u8>();
                                                    let len11 = vec11.len();
                                                    ::core::mem::forget(vec11);
                                                    *base.add(12).cast::<usize>() = len11;
                                                    *base.add(8).cast::<*mut u8>() = ptr11.cast_mut();
                                                }
                                            }
                                            *base.add(16).cast::<usize>() = len12;
                                            *base.add(12).cast::<*mut u8>() = result12;
                                        }
                                        None => {
                                            *base.add(0).cast::<u8>() = (0i32) as u8;
                                        }
                                    };
                                }
                            }
                            *ptr6.add(8).cast::<usize>() = len13;
                            *ptr6.add(4).cast::<*mut u8>() = result13;
                        }
                        Err(e) => {
                            *ptr6.add(0).cast::<u8>() = (1i32) as u8;
                            let super::super::super::super::component::grafbase::types::ErrorResponse {
                                message: message14,
                                extensions: extensions14,
                            } = e;
                            let vec15 = (message14.into_bytes()).into_boxed_slice();
                            let ptr15 = vec15.as_ptr().cast::<u8>();
                            let len15 = vec15.len();
                            ::core::mem::forget(vec15);
                            *ptr6.add(8).cast::<usize>() = len15;
                            *ptr6.add(4).cast::<*mut u8>() = ptr15.cast_mut();
                            let vec19 = extensions14;
                            let len19 = vec19.len();
                            let layout19 = _rt::alloc::Layout::from_size_align_unchecked(vec19.len() * 16, 4);
                            let result19 = if layout19.size() != 0 {
                                let ptr = _rt::alloc::alloc(layout19).cast::<u8>();
                                if ptr.is_null() {
                                    _rt::alloc::handle_alloc_error(layout19);
                                }
                                ptr
                            } else {
                                {
                                    ::core::ptr::null_mut()
                                }
                            };
                            for (i, e) in vec19.into_iter().enumerate() {
                                let base = result19.add(i * 16);
                                {
                                    let (t16_0, t16_1) = e;
                                    let vec17 = (t16_0.into_bytes()).into_boxed_slice();
                                    let ptr17 = vec17.as_ptr().cast::<u8>();
                                    let len17 = vec17.len();
                                    ::core::mem::forget(vec17);
                                    *base.add(4).cast::<usize>() = len17;
                                    *base.add(0).cast::<*mut u8>() = ptr17.cast_mut();
                                    let vec18 = (t16_1.into_bytes()).into_boxed_slice();
                                    let ptr18 = vec18.as_ptr().cast::<u8>();
                                    let len18 = vec18.len();
                                    ::core::mem::forget(vec18);
                                    *base.add(12).cast::<usize>() = len18;
                                    *base.add(8).cast::<*mut u8>() = ptr18.cast_mut();
                                }
                            }
                            *ptr6.add(16).cast::<usize>() = len19;
                            *ptr6.add(12).cast::<*mut u8>() = result19;
                        }
                    };
                    ptr6
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_authorized<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l11 = *arg0.add(4).cast::<*mut u8>();
                            let l12 = *arg0.add(8).cast::<usize>();
                            let base13 = l11;
                            let len13 = l12;
                            for i in 0..len13 {
                                let base = base13.add(i * 20);
                                {
                                    let l1 = i32::from(*base.add(0).cast::<u8>());
                                    match l1 {
                                        0 => (),
                                        _ => {
                                            let l2 = *base.add(4).cast::<*mut u8>();
                                            let l3 = *base.add(8).cast::<usize>();
                                            _rt::cabi_dealloc(l2, l3, 1);
                                            let l8 = *base.add(12).cast::<*mut u8>();
                                            let l9 = *base.add(16).cast::<usize>();
                                            let base10 = l8;
                                            let len10 = l9;
                                            for i in 0..len10 {
                                                let base = base10.add(i * 16);
                                                {
                                                    let l4 = *base.add(0).cast::<*mut u8>();
                                                    let l5 = *base.add(4).cast::<usize>();
                                                    _rt::cabi_dealloc(l4, l5, 1);
                                                    let l6 = *base.add(8).cast::<*mut u8>();
                                                    let l7 = *base.add(12).cast::<usize>();
                                                    _rt::cabi_dealloc(l6, l7, 1);
                                                }
                                            }
                                            _rt::cabi_dealloc(base10, len10 * 16, 4);
                                        }
                                    }
                                }
                            }
                            _rt::cabi_dealloc(base13, len13 * 20, 4);
                        }
                        _ => {
                            let l14 = *arg0.add(4).cast::<*mut u8>();
                            let l15 = *arg0.add(8).cast::<usize>();
                            _rt::cabi_dealloc(l14, l15, 1);
                            let l20 = *arg0.add(12).cast::<*mut u8>();
                            let l21 = *arg0.add(16).cast::<usize>();
                            let base22 = l20;
                            let len22 = l21;
                            for i in 0..len22 {
                                let base = base22.add(i * 16);
                                {
                                    let l16 = *base.add(0).cast::<*mut u8>();
                                    let l17 = *base.add(4).cast::<usize>();
                                    _rt::cabi_dealloc(l16, l17, 1);
                                    let l18 = *base.add(8).cast::<*mut u8>();
                                    let l19 = *base.add(12).cast::<usize>();
                                    _rt::cabi_dealloc(l18, l19, 1);
                                }
                            }
                            _rt::cabi_dealloc(base22, len22 * 16, 4);
                        }
                    }
                }
                pub trait Guest {
                    fn authorized(
                        context: SharedContext,
                        rule: _rt::String,
                        input: _rt::Vec<_rt::String>,
                    ) -> Result<_rt::Vec<Option<ErrorResponse>>, ErrorResponse>;
                }
                #[doc(hidden)]

                macro_rules! __export_component_grafbase_authorization_cabi{
          ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

            #[export_name = "component:grafbase/authorization#authorized"]
            unsafe extern "C" fn export_authorized(arg0: i32,arg1: *mut u8,arg2: usize,arg3: *mut u8,arg4: usize,) -> *mut u8 {
              $($path_to_types)*::_export_authorized_cabi::<$ty>(arg0, arg1, arg2, arg3, arg4)
            }
            #[export_name = "cabi_post_component:grafbase/authorization#authorized"]
            unsafe extern "C" fn _post_return_authorized(arg0: *mut u8,) {
              $($path_to_types)*::__post_return_authorized::<$ty>(arg0)
            }
          };);
        }
                #[doc(hidden)]
                pub(crate) use __export_component_grafbase_authorization_cabi;
                #[repr(align(4))]
                struct _RetArea([::core::mem::MaybeUninit<u8>; 20]);
                static mut _RET_AREA: _RetArea = _RetArea([::core::mem::MaybeUninit::uninit(); 20]);
            }
        }
    }
}
mod _rt {

    use core::fmt;
    use core::marker;
    use core::sync::atomic::{AtomicU32, Ordering::Relaxed};

    /// A type which represents a component model resource, either imported or
    /// exported into this component.
    ///
    /// This is a low-level wrapper which handles the lifetime of the resource
    /// (namely this has a destructor). The `T` provided defines the component model
    /// intrinsics that this wrapper uses.
    ///
    /// One of the chief purposes of this type is to provide `Deref` implementations
    /// to access the underlying data when it is owned.
    ///
    /// This type is primarily used in generated code for exported and imported
    /// resources.
    #[repr(transparent)]
    pub struct Resource<T: WasmResource> {
        // NB: This would ideally be `u32` but it is not. The fact that this has
        // interior mutability is not exposed in the API of this type except for the
        // `take_handle` method which is supposed to in theory be private.
        //
        // This represents, almost all the time, a valid handle value. When it's
        // invalid it's stored as `u32::MAX`.
        handle: AtomicU32,
        _marker: marker::PhantomData<T>,
    }

    /// A trait which all wasm resources implement, namely providing the ability to
    /// drop a resource.
    ///
    /// This generally is implemented by generated code, not user-facing code.
    #[allow(clippy::missing_safety_doc)]
    pub unsafe trait WasmResource {
        /// Invokes the `[resource-drop]...` intrinsic.
        unsafe fn drop(handle: u32);
    }

    impl<T: WasmResource> Resource<T> {
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
            debug_assert!(handle != u32::MAX);
            Self {
                handle: AtomicU32::new(handle),
                _marker: marker::PhantomData,
            }
        }

        /// Takes ownership of the handle owned by `resource`.
        ///
        /// Note that this ideally would be `into_handle` taking `Resource<T>` by
        /// ownership. The code generator does not enable that in all situations,
        /// unfortunately, so this is provided instead.
        ///
        /// Also note that `take_handle` is in theory only ever called on values
        /// owned by a generated function. For example a generated function might
        /// take `Resource<T>` as an argument but then call `take_handle` on a
        /// reference to that argument. In that sense the dynamic nature of
        /// `take_handle` should only be exposed internally to generated code, not
        /// to user code.
        #[doc(hidden)]
        pub fn take_handle(resource: &Resource<T>) -> u32 {
            resource.handle.swap(u32::MAX, Relaxed)
        }

        #[doc(hidden)]
        pub fn handle(resource: &Resource<T>) -> u32 {
            resource.handle.load(Relaxed)
        }
    }

    impl<T: WasmResource> fmt::Debug for Resource<T> {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            f.debug_struct("Resource").field("handle", &self.handle).finish()
        }
    }

    impl<T: WasmResource> Drop for Resource<T> {
        fn drop(&mut self) {
            unsafe {
                match self.handle.load(Relaxed) {
                    // If this handle was "taken" then don't do anything in the
                    // destructor.
                    u32::MAX => {}

                    // ... but otherwise do actually destroy it with the imported
                    // component model intrinsic as defined through `T`.
                    other => T::drop(other),
                }
            }
        }
    }
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            core::hint::unreachable_unchecked()
        }
    }

    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr as *mut u8, layout);
    }
    pub use alloc_crate::alloc;
    extern crate alloc as alloc_crate;
}

/// Generates `#[no_mangle]` functions to export the specified type as the
/// root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_hooks_impl {
  ($ty:ident) => (self::export!($ty with_types_in self););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::exports::component::grafbase::authorization::__export_component_grafbase_authorization_cabi!($ty with_types_in $($path_to_types_root)*::exports::component::grafbase::authorization);
  )
}
#[doc(inline)]
pub(crate) use __export_hooks_impl as export;

#[cfg(target_arch = "wasm32")]
#[link_section = "component-type:wit-bindgen:0.25.0:hooks:encoded world"]
#[doc(hidden)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 839] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xcb\x05\x01A\x02\x01\
A\x06\x01B\x1b\x01m\x02\x14invalid-header-value\x13invalid-header-name\x04\0\x0c\
header-error\x03\0\0\x04\0\x07context\x03\x01\x04\0\x0eshared-context\x03\x01\x04\
\0\x07headers\x03\x01\x01o\x02ss\x01p\x05\x01r\x02\x07messages\x0aextensions\x06\
\x04\0\x0eerror-response\x03\0\x07\x01h\x02\x01ks\x01@\x02\x04self\x09\x04names\0\
\x0a\x04\0\x13[method]context.get\x01\x0b\x01@\x03\x04self\x09\x04names\x05value\
s\x01\0\x04\0\x13[method]context.set\x01\x0c\x04\0\x16[method]context.delete\x01\
\x0b\x01h\x03\x01@\x02\x04self\x0d\x04names\0\x0a\x04\0\x1a[method]shared-contex\
t.get\x01\x0e\x01h\x04\x01j\x01\x0a\x01\x01\x01@\x02\x04self\x0f\x04names\0\x10\x04\
\0\x13[method]headers.get\x01\x11\x01j\0\x01\x01\x01@\x03\x04self\x0f\x04names\x05\
values\0\x12\x04\0\x13[method]headers.set\x01\x13\x04\0\x16[method]headers.delet\
e\x01\x11\x03\x01\x18component:grafbase/types\x05\0\x02\x03\0\0\x0eerror-respons\
e\x02\x03\0\0\x0eshared-context\x01B\x0b\x02\x03\x02\x01\x01\x04\0\x0eerror-resp\
onse\x03\0\0\x02\x03\x02\x01\x02\x04\0\x0eshared-context\x03\0\x02\x01i\x03\x01p\
s\x01k\x01\x01p\x06\x01j\x01\x07\x01\x01\x01@\x03\x07context\x04\x04rules\x05inp\
ut\x05\0\x08\x04\0\x0aauthorized\x01\x09\x04\x01\x20component:grafbase/authoriza\
tion\x05\x03\x04\x01\x18component:grafbase/hooks\x04\0\x0b\x0b\x01\0\x05hooks\x03\
\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.208.1\x10wit-\
bindgen-rust\x060.25.0";

#[inline(never)]
#[doc(hidden)]
#[cfg(target_arch = "wasm32")]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
