package grafbase:sdk;

world sdk {
    import access-log;
    import cache;
    import error;
    import headers;
    import http-client;
    import nats-client;
    import token;
    import directive;

    export authentication;
    export authorization;
    export init;
    export resolver;

    // The extension registration function. Must be called before initialization.
    export register-extension: func();
}
