[config]
default_to_workspace = false
skip_core_tasks = true
skip_git_env_info = true
skip_rust_env_info = true
skip_crate_env_info = true

[tasks.install-cargo-release]
private = true
install_crate = { crate_name = "cargo-release", binary = "cargo", test_arg = [
    "release",
    "--version",
], version = "0.24.10" }

[tasks.bump]
description = "Bumps the grafbase-gateway package to the specified version"
dependencies = ["install-cargo-release"]
script = '''
VERSION=${@}
cargo release version $VERSION --execute --no-confirm -p grafbase-gateway
if [[ ! -f "changelog/$VERSION.md" ]]; then
    if [[ -f "changelog/unreleased.md" ]]; then
        mv "changelog/unreleased.md" "changelog/$VERSION.md"
    else
        touch "changelog/$VERSION.md"
    fi
fi
'''

[tasks.release]
description = "Pushes a tag with the current version"
script = '''
git switch main
git pull
VERSION=$(cargo pkgid | rev | cut -d '@' -f 1 | rev)
git tag gateway-$VERSION
git push --tags
'''
