// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package authorization represents the exported interface "grafbase:sdk/authorization".
package authorization

import (
	authorizationtypes "example.com/grafbase-go-extension/grafbase/sdk/authorization-types"
	sdkerror "example.com/grafbase-go-extension/grafbase/sdk/error"
	"example.com/grafbase-go-extension/grafbase/sdk/headers"
	sharedcontext "example.com/grafbase-go-extension/grafbase/sdk/shared-context"
	"example.com/grafbase-go-extension/grafbase/sdk/token"
)

// Error represents the type alias "grafbase:sdk/authorization#error".
//
// See [sdkerror.Error] for more information.
type Error = sdkerror.Error

// ErrorResponse represents the exported type alias "grafbase:sdk/authorization#error-response".
//
// See [sdkerror.ErrorResponse] for more information.
type ErrorResponse = sdkerror.ErrorResponse

// Headers represents the exported type alias "grafbase:sdk/authorization#headers".
//
// See [headers.Headers] for more information.
type Headers = headers.Headers

// Token represents the type alias "grafbase:sdk/authorization#token".
//
// See [token.Token] for more information.
type Token = token.Token

// AuthorizationDecisions represents the type alias "grafbase:sdk/authorization#authorization-decisions".
//
// See [authorizationtypes.AuthorizationDecisions] for more information.
type AuthorizationDecisions = authorizationtypes.AuthorizationDecisions

// QueryElements represents the type alias "grafbase:sdk/authorization#query-elements".
//
// See [authorizationtypes.QueryElements] for more information.
type QueryElements = authorizationtypes.QueryElements

// ResponseElements represents the type alias "grafbase:sdk/authorization#response-elements".
//
// See [authorizationtypes.ResponseElements] for more information.
type ResponseElements = authorizationtypes.ResponseElements

// SharedContext represents the exported type alias "grafbase:sdk/authorization#shared-context".
//
// See [sharedcontext.SharedContext] for more information.
type SharedContext = sharedcontext.SharedContext
