// Code generated by wit-bindgen-go. DO NOT EDIT.

package authorization

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "grafbase:sdk/authorization".
var Exports struct {
	// AuthorizeQuery represents the caller-defined, exported function "authorize-query".
	//
	//	authorize-query: func(context: shared-context, headers: headers, token: token,
	//	elements: query-elements) -> result<tuple<authorization-decisions, list<u8>>, error-response>
	AuthorizeQuery func(context SharedContext, headers_ Headers, token_ Token, elements QueryElements) (result cm.Result[TupleAuthorizationDecisionsListU8Shape, cm.Tuple[AuthorizationDecisions, cm.List[uint8]], ErrorResponse])

	// AuthorizeResponse represents the caller-defined, exported function "authorize-response".
	//
	//	authorize-response: func(context: shared-context, state: list<u8>, elements: response-elements)
	//	-> result<authorization-decisions, error>
	AuthorizeResponse func(context SharedContext, state cm.List[uint8], elements ResponseElements) (result cm.Result[AuthorizationDecisionsShape, AuthorizationDecisions, Error])
}
