// Code generated by wit-bindgen-go. DO NOT EDIT.

package kafkaclient

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// KafkaSaslScramAuthShape is used for storage in variant or result types.
type KafkaSaslScramAuthShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(KafkaSaslScramAuth{})]byte
}

func lower_OptionString(v cm.Option[string]) (f0 uint32, f1 *uint8, f2 uint32) {
	some := v.Some()
	if some != nil {
		f0 = 1
		v1, v2 := cm.LowerString(*some)
		f1 = (*uint8)(v1)
		f2 = (uint32)(v2)
	}
	return
}

// OptionKafkaMessageShape is used for storage in variant or result types.
type OptionKafkaMessageShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(cm.Option[KafkaMessage]{})]byte
}
