// Code generated by wit-bindgen-go. DO NOT EDIT.

package kafkaclient

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "grafbase:sdk".

//go:wasmimport grafbase:sdk/kafka-client [resource-drop]kafka-producer
//go:noescape
func wasmimport_KafkaProducerResourceDrop(self0 uint32)

//go:wasmimport grafbase:sdk/kafka-client [static]kafka-producer.connect
//go:noescape
func wasmimport_KafkaProducerConnect(params *wasmimport_KafkaProducerConnect_params, result *cm.Result[string, KafkaProducer, string])

//go:wasmimport grafbase:sdk/kafka-client [method]kafka-producer.produce
//go:noescape
func wasmimport_KafkaProducerProduce(self0 uint32, key0 uint32, key1 *uint8, key2 uint32, value0 *uint8, value1 uint32, result *cm.Result[string, struct{}, string])

//go:wasmimport grafbase:sdk/kafka-client [resource-drop]kafka-consumer
//go:noescape
func wasmimport_KafkaConsumerResourceDrop(self0 uint32)

//go:wasmimport grafbase:sdk/kafka-client [static]kafka-consumer.connect
//go:noescape
func wasmimport_KafkaConsumerConnect(params *wasmimport_KafkaConsumerConnect_params, result *cm.Result[string, KafkaConsumer, string])

//go:wasmimport grafbase:sdk/kafka-client [method]kafka-consumer.next
//go:noescape
func wasmimport_KafkaConsumerNext(self0 uint32, result *cm.Result[OptionKafkaMessageShape, cm.Option[KafkaMessage], string])
