[config]
default_to_workspace = false

[tasks.install-cargo-release]
private = true
install_crate = { crate_name = "cargo-release", binary = "cargo", test_arg = [
    "release",
    "--version",
], version = "0.24.10" }

[tasks.install-sd]
private = true
install_crate = { crate_name = "sd", binary = "sd", test_arg = [
    "--version",
], version = "0.7.6" }

[tasks.bump]
dependencies = ["install-cargo-release", "install-sd"]
script = '''
VERSION=${@}

cargo release version $VERSION --execute --no-confirm

cd npm/cli
npm version --git-tag-version false $VERSION
cd ../aarch64-apple-darwin
npm version --git-tag-version false $VERSION
cd ../x86_64-apple-darwin
npm version --git-tag-version false $VERSION
cd ../x86_64-pc-windows-msvc
npm version --git-tag-version false $VERSION
cd ../x86_64-unknown-linux-musl
npm version --git-tag-version false $VERSION
cd ../
sd "@grafbase/cli-aarch64-apple-darwin\": \"\^\d+.\d+.\d+.*\"" "@grafbase/cli-aarch64-apple-darwin\": \"^$VERSION\""  cli/package.json
sd "@grafbase/cli-x86_64-apple-darwin\": \"\^\d+.\d+.\d+.*\"" "@grafbase/cli-x86_64-apple-darwin\": \"^$VERSION\""  cli/package.json
sd "@grafbase/cli-x86_64-pc-windows-msvc\": \"\^\d+.\d+.\d+.*\"" "@grafbase/cli-x86_64-pc-windows-msvc\": \"^$VERSION\""  cli/package.json
sd "@grafbase/cli-x86_64-unknown-linux-musl\": \"\^\d+.\d+.\d+.*\"" "@grafbase/cli-x86_64-unknown-linux-musl\": \"^$VERSION\""  cli/package.json
'''

[tasks.release]
script = '''
git switch main
git pull
cd crates/cli
VERSION=$(cargo pkgid | rev | cut -d '@' -f 1 | rev)
cd ../..
git tag $VERSION
git push --tags
'''

[tasks.prettier]
script = '''
npx prettier --write .
'''

[tasks.test]
clear = true
command = "cargo"
args = ["nextest", "run"]

[tasks.clippy]
clear = true
command = "cargo"
args = ["clippy", "--locked", "--tests", "--", "-D", "warnings"]

[tasks.clippy-nightly]
toolchain = "nightly"
command = "cargo"
args = ["clippy", "--locked", "--tests", "--", "-D", "warnings"]

[tasks.run]
clear = true
command = "cargo"
args = ["run", "--", "${@}"]

[tasks.run-release]
clear = true
command = "cargo"
args = ["run", "--release", "--", "${@}"]

[tasks.update-workers]
script = '''
cd ../../api/workers/gateway
RELEASE_FLAG="--dev" ../../scripts/dev/build-cli-assets.sh
'''

[tasks.update-workers-main]
script = '''
cd ../../api/workers/gateway
git switch main
git pull
RELEASE_FLAG="--dev" ../../scripts/dev/build-cli-assets.sh
'''

[tasks.update-workers-release]
script = '''
cd ../../api/workers/gateway
../../scripts/dev/build-cli-assets.sh
'''

[tasks.update-workers-main-release]
script = '''
cd ../../api/workers/gateway
git switch main
git pull
../../scripts/dev/build-cli-assets.sh
'''
