// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package hooks represents the exported interface "grafbase:sdk/hooks".
package hooks

import (
	sdkerror "example.com/grafbase-go-extension/grafbase/sdk/error"
	eventqueue "example.com/grafbase-go-extension/grafbase/sdk/event-queue"
	"example.com/grafbase-go-extension/grafbase/sdk/headers"
	httpclient "example.com/grafbase-go-extension/grafbase/sdk/http-client"
	sharedcontext "example.com/grafbase-go-extension/grafbase/sdk/shared-context"
)

// HTTPMethod represents the type alias "grafbase:sdk/hooks#http-method".
//
// See [httpclient.HTTPMethod] for more information.
type HTTPMethod = httpclient.HTTPMethod

// ErrorResponse represents the exported type alias "grafbase:sdk/hooks#error-response".
//
// See [sdkerror.ErrorResponse] for more information.
type ErrorResponse = sdkerror.ErrorResponse

// Headers represents the exported type alias "grafbase:sdk/hooks#headers".
//
// See [headers.Headers] for more information.
type Headers = headers.Headers

// SharedContext represents the exported type alias "grafbase:sdk/hooks#shared-context".
//
// See [sharedcontext.SharedContext] for more information.
type SharedContext = sharedcontext.SharedContext

// EventQueue represents the exported type alias "grafbase:sdk/hooks#event-queue".
//
// See [eventqueue.EventQueue] for more information.
type EventQueue = eventqueue.EventQueue
