// Code generated by wit-bindgen-go. DO NOT EDIT.

package resolvertypes

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// ResponseShape is used for storage in variant or result types.
type ResponseShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(Response{})]byte
}
