interface shared-context {
    use token.{token};

    /// A shared context resource that provides access to tracing and event handling capabilities
    resource shared-context {
        hook-state: func() -> list<u8>;
        authentication-token: func() -> token;
        authorization-state: func(key: option<string>) -> result<list<u8>, string>;

        /// Pushes a new event to the end of the request event queue.
        push-event: func(name: string, data: list<u8>);
    }
}
