/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_grafbasegateway_free(a: number): void;
export function grafbasegateway_new(a: number, b: number, c: number): void;
export function grafbasegateway_execute(a: number, b: number, c: number): number;
export function __wbg_queuingstrategy_free(a: number): void;
export function queuingstrategy_highWaterMark(a: number): number;
export function __wbg_intounderlyingbytesource_free(a: number): void;
export function intounderlyingbytesource_type(a: number, b: number): void;
export function intounderlyingbytesource_autoAllocateChunkSize(a: number): number;
export function intounderlyingbytesource_start(a: number, b: number): void;
export function intounderlyingbytesource_pull(a: number, b: number): number;
export function __wbg_intounderlyingsource_free(a: number): void;
export function intounderlyingsource_pull(a: number, b: number): number;
export function intounderlyingsource_cancel(a: number): void;
export function readablestreamgetreaderoptions_mode(a: number): number;
export function __wbg_pipeoptions_free(a: number): void;
export function pipeoptions_preventClose(a: number): number;
export function pipeoptions_preventCancel(a: number): number;
export function pipeoptions_preventAbort(a: number): number;
export function pipeoptions_signal(a: number): number;
export function __wbg_intounderlyingsink_free(a: number): void;
export function intounderlyingsink_write(a: number, b: number): number;
export function intounderlyingsink_close(a: number): number;
export function intounderlyingsink_abort(a: number, b: number): number;
export function __wbg_minifyconfig_free(a: number): void;
export function __wbg_get_minifyconfig_js(a: number): number;
export function __wbg_set_minifyconfig_js(a: number, b: number): void;
export function __wbg_get_minifyconfig_html(a: number): number;
export function __wbg_set_minifyconfig_html(a: number, b: number): void;
export function __wbg_get_minifyconfig_css(a: number): number;
export function __wbg_set_minifyconfig_css(a: number, b: number): void;
export function __wbg_get_r2range_offset(a: number, b: number): void;
export function __wbg_set_r2range_offset(a: number, b: number, c: number): void;
export function __wbg_get_r2range_length(a: number, b: number): void;
export function __wbg_set_r2range_length(a: number, b: number, c: number): void;
export function __wbg_get_r2range_suffix(a: number, b: number): void;
export function __wbg_set_r2range_suffix(a: number, b: number, c: number): void;
export function intounderlyingbytesource_cancel(a: number): void;
export function __wbg_readablestreamgetreaderoptions_free(a: number): void;
export function __wbg_r2range_free(a: number): void;
export function __wbindgen_export_0(a: number): number;
export function __wbindgen_export_1(a: number, b: number, c: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function __wbindgen_export_3(a: number, b: number): void;
export function __wbindgen_export_4(a: number, b: number, c: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_export_5(a: number, b: number): void;
export function __wbindgen_export_6(a: number): void;
export function __wbindgen_export_7(a: number, b: number, c: number, d: number): void;
