// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package sharedcontext represents the imported interface "grafbase:sdk/shared-context".
package sharedcontext

import (
	"go.bytecodealliance.org/cm"
)

// SharedContext represents the imported resource "grafbase:sdk/shared-context#shared-context".
//
// A shared context resource that provides access to tracing and event handling capabilities
//
//	resource shared-context
type SharedContext cm.Resource

// ResourceDrop represents the imported resource-drop for resource "shared-context".
//
// Drops a resource handle.
//
//go:nosplit
func (self SharedContext) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_SharedContextResourceDrop((uint32)(self0))
	return
}

// PushEvent represents the imported method "push-event".
//
// Pushes a new event to the end of the request event queue.
//
//	push-event: func(name: string, data: list<u8>)
//
//go:nosplit
func (self SharedContext) PushEvent(name string, data cm.List[uint8]) {
	self0 := cm.Reinterpret[uint32](self)
	name0, name1 := cm.LowerString(name)
	data0, data1 := cm.LowerList(data)
	wasmimport_SharedContextPushEvent((uint32)(self0), (*uint8)(name0), (uint32)(name1), (*uint8)(data0), (uint32)(data1))
	return
}

// TraceID represents the imported method "trace-id".
//
// Returns the request trace identifier as a string
//
//	trace-id: func() -> string
//
//go:nosplit
func (self SharedContext) TraceID() (result string) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_SharedContextTraceID((uint32)(self0), &result)
	return
}
