import { HoudiniClient } from '$houdini';
import { PUBLIC_GRAFBASE_API_URL } from '$env/static/public';
import { authToken } from '$lib/shared/stores/token';

export default new HoudiniClient({
	url: PUBLIC_GRAFBASE_API_URL,
	fetchParams() {
		return {
			headers: {
				// Token generated by your auth provider: https://grafbase.com/docs/reference/directives#auth
				Authorization: `Bearer ${authToken}`
			}
		};
	}
});
