interface context {
    use headers.{headers};
    use token.{token};

    // The context as a read-only object.
    resource shared-context {
        // Fetches a context value with the given name, if existing.
        get: func(name: string) -> option<string>;
        // Gets the current trace-id.
        trace-id: func() -> string;
    }

    resource authorization-context {
        headers: func() -> headers;
        token: func() -> token;
    }
}
