// Code generated by wit-bindgen-go. DO NOT EDIT.

package authentication

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "grafbase:sdk".

//go:wasmexport grafbase:sdk/authentication#authenticate
//export grafbase:sdk/authentication#authenticate
func wasmexport_Authenticate(context0 uint32, headers0 uint32) (result *cm.Result[ErrorResponseShape, Token, ErrorResponse]) {
	context := cm.Reinterpret[SharedContext]((uint32)(context0))
	headers_ := cm.Reinterpret[Headers]((uint32)(headers0))
	result_ := Exports.Authenticate(context, headers_)
	result = &result_
	return
}

//go:wasmexport grafbase:sdk/authentication#public-metadata
//export grafbase:sdk/authentication#public-metadata
func wasmexport_PublicMetadata() (result *cm.Result[ErrorShape, cm.List[PublicMetadataEndpoint], Error]) {
	result_ := Exports.PublicMetadata()
	result = &result_
	return
}
