// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package authentication represents the exported interface "grafbase:sdk/authentication".
package authentication

import (
	sdkerror "example.com/grafbase-go-extension/grafbase/sdk/error"
	"example.com/grafbase-go-extension/grafbase/sdk/headers"
	sharedcontext "example.com/grafbase-go-extension/grafbase/sdk/shared-context"
	"example.com/grafbase-go-extension/grafbase/sdk/token"
	"go.bytecodealliance.org/cm"
)

// Headers represents the exported type alias "grafbase:sdk/authentication#headers".
//
// See [headers.Headers] for more information.
type Headers = headers.Headers

// ErrorResponse represents the exported type alias "grafbase:sdk/authentication#error-response".
//
// See [sdkerror.ErrorResponse] for more information.
type ErrorResponse = sdkerror.ErrorResponse

// Error represents the type alias "grafbase:sdk/authentication#error".
//
// See [sdkerror.Error] for more information.
type Error = sdkerror.Error

// Token represents the type alias "grafbase:sdk/authentication#token".
//
// See [token.Token] for more information.
type Token = token.Token

// SharedContext represents the exported type alias "grafbase:sdk/authentication#shared-context".
//
// See [sharedcontext.SharedContext] for more information.
type SharedContext = sharedcontext.SharedContext

// PublicMetadataEndpoint represents the exported record "grafbase:sdk/authentication#public-metadata-endpoint".
//
// An HTTP endpoint exposed publicly on the Gateway. This is typically used to return
// metadata for authentication purposes, for example with the [OAuth 2.0 Protected
// Resource Metadata](https://datatracker.ietf.org/doc/html/rfc9728) spec.
//
//	record public-metadata-endpoint {
//		path: string,
//		response-body: list<u8>,
//		response-headers: headers,
//	}
type PublicMetadataEndpoint struct {
	_ cm.HostLayout `json:"-"`
	// The absolute path (without domain) of the endpoint. Example: "/.well-known/oauth-protected-resource".
	Path string `json:"path"`

	// The contents of the response body that the endpoint will return. Example: '{"resource":
	// "https://secure.example.com" }'.
	ResponseBody cm.List[uint8] `json:"response-body"`

	// The headers sent from with the response by the public endpoint. Example: ["Content-Type:
	// application/json"].
	ResponseHeaders Headers `json:"response-headers"`
}
