// Code generated by wit-bindgen-go. DO NOT EDIT.

package schema

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// ObjectDefinitionShape is used for storage in variant or result types.
type ObjectDefinitionShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(ObjectDefinition{})]byte
}

// FieldDefinitionDirectiveSiteShape is used for storage in variant or result types.
type FieldDefinitionDirectiveSiteShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(FieldDefinitionDirectiveSite{})]byte
}
