// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package sdkerror represents the imported interface "grafbase:sdk/error".
package sdkerror

import (
	"example.com/grafbase-go-extension/grafbase/sdk/headers"
	"go.bytecodealliance.org/cm"
)

// Headers represents the imported type alias "grafbase:sdk/error#headers".
//
// See [headers.Headers] for more information.
type Headers = headers.Headers

// Error represents the record "grafbase:sdk/error#error".
//
// An error response can be used to inject an error to the GraphQL response.
//
//	record error {
//		extensions: list<tuple<string, list<u8>>>,
//		message: string,
//	}
type Error struct {
	_ cm.HostLayout `json:"-"`
	// Adds the given extensions to the response extensions. The first item in
	// the tuple is the extension key, and the second item is the extension value encoded
	// in CBOR
	Extensions cm.List[cm.Tuple[string, cm.List[uint8]]] `json:"extensions"`

	// The error message.
	Message string `json:"message"`
}

// ErrorResponse represents the imported record "grafbase:sdk/error#error-response".
//
// An HTTP error response.
//
//	record error-response {
//		status-code: u16,
//		errors: list<error>,
//		headers: option<headers>,
//	}
type ErrorResponse struct {
	_ cm.HostLayout `json:"-"`
	// HTTP status code. Must be a valid status code. If not, the status code will be
	// 500.
	StatusCode uint16 `json:"status-code"`

	// List of GraphQL errors.
	Errors cm.List[Error] `json:"errors"`

	// The headers to send with the response. Keys and values must be ASCII strings.
	Headers cm.Option[Headers] `json:"headers"`
}
