[v1]
"cargo-about 0.6.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-about"]
"cargo-bloat 0.12.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-bloat"]
"cargo-expand 1.0.90 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-expand"]
"cargo-hakari 0.9.31 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-hakari"]
"cargo-instruments 0.4.8 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-instruments"]
"cargo-release 0.24.10 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-release"]
"dprint 0.47.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["dprint"]
"hexyl 0.14.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["hexyl"]
