// Code generated by wit-bindgen-go. DO NOT EDIT.

package natsclient

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "grafbase:sdk".

//go:wasmimport grafbase:sdk/nats-client [resource-drop]nats-client
//go:noescape
func wasmimport_NatsClientResourceDrop(self0 uint32)

//go:wasmimport grafbase:sdk/nats-client [static]nats-client.connect
//go:noescape
func wasmimport_NatsClientConnect(servers0 *string, servers1 uint32, auth0 uint32, auth1 uint32, auth2 uint32, auth3 uint32, auth4 *uint8, auth5 uint32, result *cm.Result[string, NatsClient, string])

//go:wasmimport grafbase:sdk/nats-client [method]nats-client.key-value
//go:noescape
func wasmimport_NatsClientKeyValue(self0 uint32, bucket0 *uint8, bucket1 uint32, result *cm.Result[string, NatsKeyValue, string])

//go:wasmimport grafbase:sdk/nats-client [method]nats-client.publish
//go:noescape
func wasmimport_NatsClientPublish(self0 uint32, subject0 *uint8, subject1 uint32, message0 *uint8, message1 uint32, result *cm.Result[string, struct{}, string])

//go:wasmimport grafbase:sdk/nats-client [method]nats-client.request
//go:noescape
func wasmimport_NatsClientRequest(self0 uint32, subject0 *uint8, subject1 uint32, message0 *uint8, message1 uint32, timeoutMs0 uint32, timeoutMs1 uint64, result *cm.Result[NatsMessageShape, NatsMessage, string])

//go:wasmimport grafbase:sdk/nats-client [method]nats-client.subscribe
//go:noescape
func wasmimport_NatsClientSubscribe(params *wasmimport_NatsClientSubscribe_params, result *cm.Result[string, NatsSubscriber, string])

//go:wasmimport grafbase:sdk/nats-client [resource-drop]nats-key-value
//go:noescape
func wasmimport_NatsKeyValueResourceDrop(self0 uint32)

//go:wasmimport grafbase:sdk/nats-client [method]nats-key-value.create
//go:noescape
func wasmimport_NatsKeyValueCreate(self0 uint32, key0 *uint8, key1 uint32, value0 *uint8, value1 uint32, result *cm.Result[string, uint64, string])

//go:wasmimport grafbase:sdk/nats-client [method]nats-key-value.delete
//go:noescape
func wasmimport_NatsKeyValueDelete(self0 uint32, key0 *uint8, key1 uint32, result *cm.Result[string, struct{}, string])

//go:wasmimport grafbase:sdk/nats-client [method]nats-key-value.get
//go:noescape
func wasmimport_NatsKeyValueGet(self0 uint32, key0 *uint8, key1 uint32, result *cm.Result[OptionListU8Shape, cm.Option[cm.List[uint8]], string])

//go:wasmimport grafbase:sdk/nats-client [method]nats-key-value.put
//go:noescape
func wasmimport_NatsKeyValuePut(self0 uint32, key0 *uint8, key1 uint32, value0 *uint8, value1 uint32, result *cm.Result[string, uint64, string])

//go:wasmimport grafbase:sdk/nats-client [resource-drop]nats-subscriber
//go:noescape
func wasmimport_NatsSubscriberResourceDrop(self0 uint32)

//go:wasmimport grafbase:sdk/nats-client [method]nats-subscriber.next
//go:noescape
func wasmimport_NatsSubscriberNext(self0 uint32, result *cm.Result[OptionNatsMessageShape, cm.Option[NatsMessage], string])
